spring.application.name=sejasenai

spring.datasource.url=jdbc:mysql://localhost:3306/sige
spring.datasource.username=u2724_mUW5Q8ueu5
spring.datasource.password=cb@j8=Qipw!^yxq^3GtxSX5E

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080