spring.application.name=SejaSenai

spring.datasource.url=jdbc:mysql://SEU_HOST_INTERNO.com:3306:3306/sige
spring.datasource.username=u2724_mUW5Q8ueu5
spring.datasource.password=cb@j8=Qipw!^yxq^3GtxSX5E

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true