spring.application.name=SejaSenai

spring.datasource.url=jdbc:mysql://nac-00.haskhosting.com.br:3306:3306/s2724_wuzuy
spring.datasource.username=u2724_mUW5Q8ueu5
spring.datasource.password=cb@j8=Qipw!^yxq^3GtxSX5E

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true